Game_Title:str = "|TEXT|\n[Apex Adventures: Mad Maggie]\n"
Game_Description:str = "|TEXT|\nGame Description:\nYou are, fellow adventurer, are the fiercest warlord the universe has ever met.\nUnfortunately, you've been sentenced to fight again and again in the Apex Games\nA bloodsport competition where squads of 3 battle to the death,\nuntil you are eventually killed with no chance of revival."
Game_Instructions:str = "|PROMPT|\nGame Instructions:\nTo progress through the game simply press the enter key.\nValid Commands:\nEXAMINE: Find info on current location\nHELP: Display all valid commands\nQUIT: End game abruptly\nSAVE: Create a save file which you can nanme\nLOAD: Load in a pre-made save file\nThere are two ways this journey can end,\n1. You probably die somewhere along the road.\n2. Or maybe you manage to reach the end, becoming the Apex Champion!\n"
Stop_A_Text_List = [Game_Title,"|PROMPT|\nPress Enter to Continue",Game_Description,"|SET|\nWhat will your name will be?",Game_Instructions,"|PROMPT|\nThe Apex Legends think you're all talk \nlets show em how bad you can be, shall we?"]
Game_Credits_0 = "|TEXT|\n*GOOD ENDING*\nYou have become the Apex Champion! \nCongrats :)\n \nThanks for playing My Project. \nIt took a while to do \nso hopefully I'll get a good grade!\n:)"
Game_Copyright = "|TEXT|\n© 2022 Solomon Henry Corporations"
Stop_F_Text_List = [Game_Credits_0,Game_Copyright]
Stop_Quit_Text_0 = "|TEXT|\n*QUIT ENDING*\nYou have quit.\n:(\nJust remember that you can try again!\n"
Stop_Quit_Text_List = [Stop_Quit_Text_0]
Stop_Death_Text_0 = "|TEXT|\n*DEATH ENDING*\nSadly you died. No championship for you.\nMaybe next time :("
Stop_Death_Text_List = [Stop_Death_Text_0]
Stop_0:str = "Courtroom"
Stop_0_Text_0:str = "|TEXT|'|USERNAME|',the judge says"
Stop_0_Text_1:str = "|TEXT|\n'Whatever, you've been charged with 27 counts of sedition.\nincluding 18 counts of inciting riots\nagainst the Syndicate Alliance of Free Worlds"
Stop_0_Text_2:str = "|TEXT|\n'9 counts of raiding Syndicate transport ships \nbut of course, that all pales to your true crimes \nyou masterminding the cold-blooded attack on the \nSalvo-Syndicate Merger Ceremony.' \n'What is your deleluded self-justifcation for all that bloodshed, huh?'"
Stop_0_Text_3:str = "|TEXT|\n'Such a coward, taking the lives of so many in the name of justice \nbut in the end it was all pointless.\nHere and now you and your crimes will come to an end"
Stop_0_Text_4:str = "|TEXT|\n'GAHHHH' the judge screams in pain shielding his eye.\n'Take her away, the guards yell'\n*You are taken out of the courtroom,\nlaughing as you see the judge hollowing in pain.*"
Stop_0_Text_List = [Stop_0_Text_0,"|PROMPT|\nIt's |USERNAME|!",Stop_0_Text_1,"|PROMPT|\nBig Words for a buncha of Dictators!",Stop_0_Text_2,"|PROMPT|\nThere is always a price to freedom",Stop_0_Text_3,"|PROMPT|\n*You then proceed to dislodge your tooth a metal railing then you shot tooth into the judge's eye*","|PROMPT|\nSalvo is a free world! No matter whose flag you shove in her soil!",Stop_0_Text_4,"|PROMPT|\nYou are prepared for your execution, but the judge appears soon comes to your execution place.\nWhat exactly has he come here for?"]
Stop_1:str = "Dropship"
Stop_1_Text_0:str = "|TEXT|\n*You have been transported to a dropship,\nto where you are flying, you don't know*"
Stop_1_Text_1:str = "|TEXT|\n'I may be your judge and jury, but I am not your executioner' the now one-eyed judge says\n'All of the outlands shall see you death.\n So you shall be heading to the Apex Games,\n where the public shall enjoy your death at the hands of our beloved Apex Legends'"
Stop_1_Text_List = [Stop_1_Text_0,Stop_1_Text_1,"|PROMPT|\n*Ha ha ha ha* Lets see em bloody try to kill me!"]
Stop_2:str = "Hammond Labs"
Stop_2_Text_0:str = "|TEXT|\nYou are unceremoniously booted off of the dropship,\nalmost falling to your doom if it wasn't for your jump-jets breaking your fall.\nBut now isn't the time to relax as you are now in the Apex Games.\nWait, didn't you see somethings on the ground as you were falling?"
Stop_2_Text_1:str = "|TEXT|\nWell well well, speaking of Apex Legends,\nyou've just come in contact with a squad of 3 of them\nThis squad consists of:\nCrypto, the Surveillance Expert, whose drone seeks out and EMPS enemies; \nHorizon, the 100+ year old(Thanks to being trapped near a black hole) Gravitational Manipulator,\nwhose aresenal consist of a literal black hole;\nand last (and probably least) Mirage, the Holographic Trickster,\nhis invisibility along with his holographic decoys are just annoying"
Stop_2_Text_2:str = "|TEXT|\nAnd now they have spotted you and are preparing to have you meet your maker?\nWhat are you gonna do?"
Stop_2_Text_3:str = "|TEXT|\nGood idea, 1v3s are not really fair. You gonna need a team.\nYou know that you were assigned team members,\nbut for the life of you, you can't seem to find them.\nBut that doesn't matter now, this thirsty squad is hot on your heels.\nYou gotta do something, but what?"
Stop_2_Text_4:str = "|TEXT|\nYou round a corner and shoot your riot drill into it as you pass it.\nThe riot drill drills through the wall and spurts out fire, singeing Crypto.\n'Ha' you say as you get away"
Stop_2_Text_List = [Stop_2_Text_0,"|PROMPT|\n*Turn around*",Stop_2_Text_1,Stop_2_Text_2,"|PROMPT|\nRun for your life",Stop_2_Text_3,"|PROMPT|\nLooks like time for your riot drill",Stop_2_Text_4,"|CHOICE|\nLets see if there is any good loot in Estates, shall we?"]
Stop_3:str = "Estates"
Stop_3_Text_0:str = "|TEXT|\nGood news: You have evaded the enemy squad and have arrived in a nice place called Estates. \nBad news: There are like 5 other squads here."
Stop_3_Text_1:str = "|TEXT|\nAlrighty, looks like you gotta be anywhere, but here.\nOkay plan B, lets, wait wha?"
Stop_3_Text_List = [Stop_3_Text_0,"|PROMPT|\nStart booking it outta there",Stop_3_Text_1,"|PROMPT|\nEy, what the AHHHHh!!!"]
Stop_4:str = "Secret Trapdoor"
Stop_4_Text_0:str = "|TEXT|\nWell, it seems that you have fallen through what seems to be a secret trapdoor.\nYou cautiously move up ahead to find a Phase Engine.\nAn engine that uses materials that can warp space time, to help the floating city of Olympus stay afloat.\nThough it does quite beautiful, with all that material flowing seamlessly in a sphere"
Stop_4_Text_1:str = "|TEXT|\nAs you get closer to the phase engine,\nyou fail to see the bright warning sign that explicitly states don't go near the engine. \nYou're then sucked in by the machine's gravitational pull.\nNow to scream like a maniac"
Stop_4_Text_List = [Stop_4_Text_0,"|PROMPT|\nGet close to such a beautiful sight",Stop_4_Text_1,"|PROMPT|\nAAUUUGGGHHHHHH!!!!!"]
Stop_5:str = "Phase Driver"
Stop_5_Text_0:str = "|TEXT|\nIt seems that the phase engine has teleported you to another phase engine,\nthis one being in the aptly named location Phase Driver.\nA nice location with random objects partly phased into reality and 2 squads killing each other"
Stop_5_Text_1:str = "|TEXT|\nStrangely, the teams aren't glaring at you though,\nthey are actually staring at the phase engine behind you.\nWhat is it they could possibly be looking at? "
Stop_5_Text_2:str = "|TEXT|\nWell great, the phase engine is going out of control thanks to your meddling.\nAnd now everything is being phased and teleported into a random place.\nWell, what are you going to do now, oh fierce warlord?"
Stop_5_Text_List = [Stop_5_Text_0,"|PROMPT|\nWait wuh?",Stop_5_Text_1,"|PROMPT|\n*Turn around*",Stop_5_Text_2,"|CHOICE|\nRun for your life and blindly going into a phasing building"]
Stop_6:str = "Solar Array"
Stop_6_Text_0:str = "|TEXT|\nYou get teleported into Solar Array, at least this place seems free of enemies.\nBut wait, you see two figures overlooking you from a nearby building.\nWho could they be?"
Stop_6_Text_1:str = "|TEXT|\nWell this just got interesting you finally found your 2 other teamates!\nNow you got Octane, the High-Speed Daredevil,\nwho is constantly injecting himself with 'stim'(God knows whats in that) to go faster,\nand Lifeline, the Combat Medic,\nwho is just there to resuscitate people with her Med-drone.  "
Stop_6_Text_2:str = "|TEXT|\n*Octane tosses you a Eva-8 shotgun* (About time you got a weapon)\n'Really' Lifeline says with disbelief.\n'Like it or not, she's on our squad chica. We gotta work with her' Octane replies\n'ATTENTION! FINAL CIRCLE WILL BE AT BONSAI PALACE! LAST 2 SQUADS GO THERE OR BE DISQUALIFIED!'"  
Stop_6_Text_List = [Stop_6_Text_0,"|PROMPT|\n*Squint, looking in their direction*",Stop_6_Text_1,"|PROMPT|\nCome on then, Lets get the dub!",Stop_6_Text_2,"|CHOICE|\n'I'm gonna go kill the last squad, so you lot betta stay outta my way!'"]
Stop_7:str = "Bonsai Palace"
Stop_7_Text_0:str = "|TEXT|\nYou with your newly found teamates arrive to Bonsai Palace on time.\nAnd as if on cue, the enemy team comes up the opposing hill.\nIt seems this team has Pathfinder, the Forward Scout,\napparently a scouting robot that wandered into the Apex Games;\nWraith, the Interdimensonal Skirmisher, who can phase in and out of reality;\nand finally, wait it can't be!\nFuse, a.k.a The Bombastic Explosives Expert, a.k.a your old friend turned traitor.\nHow will you go about seeing your old friend?"
Stop_7_Text_1:str = "|TEXT|\nYou and your team rush at the enemy team who is also doing the same. It all turns to chaos then.\nLifeline begins fighting Pathfinder swinging from the sky.\nOctane begins shooting at Wraith, who just phased out of reality.\nAnd you gun it straight for Fuse.\nFuse, scared that someone he thought was dead is coming to kill him,\nshoots his incenidary missile 'The Motherlode' at you, exploding on impact.\nThere's no way you could have survived, right?"
Stop_7_Text_2:str = "|TEXT|\nEveryone is looking at the explosion,\nprobably thinking that you didn't last so long for all your hype.\nBut then your 'Wrecking Ball',\na metal ball that haphazardly bounces around,\ncomes out of the fire and hits Fuse squarely in the chest,knocking him down\nYou survived thanks to the Wrecking Ball tanking the explosion for you.\nYou then run up to Fuse and shoot him right in the chest, killing him.\nHe'll definitely be revived later, so this isn't the last you've seen of Fuse.\nThough on the bright side, you aren't the only one to win their fight.\nLifeline, the useless medic, took out Pathfinder, the equally useless robot,\nwhile Octane shot Wraith as she phased back into reality"
Stop_7_Text_List = [Stop_7_Text_0,"|PROMPT|\nLETS KILL EM",Stop_7_Text_1,"|PROMPT|\nHell Yeah You Do!",Stop_7_Text_2,"|PROMPT|\nVictory Screech!!!"]
Stop_8:str = "Champion's Podium"
Stop_8_Text_0:str = "|TEXT|'!' booms a computerized voice"
Stop_8_Text_1:str = "|TEXT|\nYour excitement is short lived as Syndicate police soon take you away in a police dropship"
Stop_8_Text_List = [Stop_8_Text_0,"|PROMPT|\nTakes a lot more than that to kill the Me!",Stop_8_Text_1,"|PROMPT|'Back to Jail Already? Aww, I was just startin to have fun!" ]
Stop_9:str = "Prison Dropship"
Stop_9_Text_0:str = "|PROMPT|\nYou are transported back to jail, awaiting the next Apex game.\nThose syndicate dogs think that they can put you down,\nbut one day you will have the last laugh"
Stop_9_Text_List = [Stop_9_Text_0]